language: node_js
dist: trusty

node_js:
  - "node"
env:
  - TEST_SUITE=unit-test
  - TEST_SUITE=e2e-test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - chromium-browser
      - chromium-chromedriver
before_install:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script: "gulp $TEST_SUITE"
